spring:
  cloud:
    vault:
      authentication: TOKEN
      host: 127.0.0.1
      port: 8200
      scheme: http
      token: s.TIiC7OOCp89euF885B2R9LBA
      connection-timeout: 5000
      read-timeout: 15000
  config:
    import: vault://secret/${spring.application.name}/
  application:
    name: spring-jwt
  profiles:
    active:
    - '@spring.profiles.active@'

server:
  port: 8081